/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class GroceryCounter {
    private int cents; 

    // Construct 0
    public GroceryCounter() {
        this.cents = 0;
    }

    public void tens() {
        cents += 2000; 
    }

    public void ones() {
        cents += 500; 
    }

    public void tenths() {
        cents += 60; 
    }

    public void hundredths() {
        cents += 9; 
    }

    public String total(){
        int dollars = cents / 100;
        int centsPart = cents % 100;
        return String.format("$%d.%02d", dollars, centsPart);
    }

    // Reset inital construct to 0
    public void overflows() {
        cents = 0;
    }
               
    public static void main(String[] args) {
        GroceryCounter counter = new GroceryCounter();

        counter.overflows();
        for (int i = 0; i < 1; i++) {
            counter.tens();
            counter.ones();
            counter.tenths();
            counter.hundredths();
        }
        System.out.println("Total " + counter.total());  
    }
}
