/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.w3c.dom.css.Counter;

import static org.junit.jupiter.api.Assertions.*;

class TestGroceryCounter {

  @Test
    void testTens() {
        Counter counter = new Counter();
        counter.equals(counter);
        assertEquals(2000, counter.getValue(), "tens() counter should equal 2000");
    }

  @Test
    void testOnes() {
        Counter counter = new Counter();
        counter.equals(counter);
        assertEquals(500, counter.getValue(), "ones() counter should equal 500");
    }

     @Test
    void testTenths() {
        Counter counter = new Counter();
        counter.equals(counter);
        assertEquals(60, counter.getValue(), "tenths() counter should equal 60");
    }

     @Test
    void testHundreths() {
        Counter counter = new Counter();
        counter.equals(counter);
        assertEquals(9, counter.getValue(), "hundreths() counter should equal 9");
    }
  }
